#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {execFileSync} from 'node:child_process';
import {V13_SECTION48_QUALIFICATION_LANES} from '../js/glaze-v1.7-v1-3-qualification.dev.mjs';
import {V13_SECTION48_COVERAGE_LANES} from '../js/glaze-v1.7-v1-3-qualification-coverage.dev.mjs';
import {evaluateGlazePerformanceMeasurements} from '../js/glaze-v1.6-performance-diagnostics.dev.mjs';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const read=rel=>fs.readFileSync(path.join(root,rel),'utf8');
const json=rel=>JSON.parse(read(rel));
const req=(value,message)=>{if(!value)throw new Error(message);};
const SOURCE='4b9d085a5177b96cc31d4270b38d792a59872e37';
const SOURCE_MODEL='1.7.0-dev.47';
const STABLE='1.7.0';
const HISTORICAL='1.6.0';
const HEX40=/^[0-9a-f]{40}$/;
const PLACEHOLDER=/(REPLACE_WITH|\bTBD\b|\bTODO\b|template placeholder)/i;
const types=['human','device','assistive-technology','performance','energy'];
const plan=json('contracts/v1.7/qualification.v1.3.field.plan.json');
const energyMethodPlan=json('contracts/v1.7/qualification.v1.2.energy.plan.json');
const schema=json('schemas/v1.7.1-section48-field-qualification-plan.schema.json');
const lifecycle=json('registry/lifecycle.json');
const procedure=read('acceptance/v1.7.1-section48-field-qualification.md');
const templates=Object.fromEntries(types.map(t=>[t,json('acceptance/v1.7.1-section48-'+t+'-evidence.template.json')]));
const allLanes=[...V13_SECTION48_QUALIFICATION_LANES,...V13_SECTION48_COVERAGE_LANES];
const laneMap=new Map(allLanes.map(l=>[l.id,l]));
const expected={
 human:['workspace-continuity-v13','agent-activity-authority-v13','privacy-attention-authority-v13','accessibility-presentation-v13','creative-state-separation-v13','compare-neutrality-v13','care-authority-v13','large-text-reflow-v13','forced-colors-v13','keyboard-continuity-v13','switch-access-v13','voice-access-v13','provider-integration-v13','privacy-security-integration-v13','cross-platform-expression-v13','human-visual-v13','expression-system-v13','contextual-actions-v13','brief-v13','control-center-v13'],
 device:['workspace-continuity-v13','compact-surface-v13','large-text-reflow-v13','compact-device-behavior-v13','cross-platform-expression-v13','energy-v13'],
 'assistive-technology':['compact-surface-v13','accessibility-presentation-v13','large-text-reflow-v13','forced-colors-v13','switch-access-v13','voice-access-v13'],
 performance:['performance-v13'], energy:['energy-v13']
};
function meaningful(value,label){req(typeof value==='string'&&value.trim(),label+' must be non-empty'); const s=value.trim(); req(!PLACEHOLDER.test(s),label+' contains placeholder'); return s;}
function git(...args){return execFileSync('git',args,{cwd:root,encoding:'utf8'}).trim();}
function validDate(v){return typeof v==='string'&&!Number.isNaN(Date.parse(v));}
function authorityFalse(a,key){req(a&&a[key]===false,'authority boundary must remain false: '+key);}
function observations(items){req(Array.isArray(items)&&items.length>0,'observations must be non-empty'); for(const [i,x] of items.entries()){req(x&&typeof x==='object'&&!Array.isArray(x),'observation '+i+' must be object'); meaningful(x.id,'observation id'); req(['pass','fail','not-applicable-with-reason'].includes(x.status),'observation status invalid'); meaningful(x.observation,'observation text');}}

function validateSource(){
 req(schema.$schema==='https://json-schema.org/draft/2020-12/schema','schema dialect drifted');
 req(plan.planId==='goreecloud.glaze.v1.7.1.section48-field-qualification','plan ID drifted');
 req(plan.lifecycle==='DevelopmentQualification'&&plan.successorReleaseLine==='1.7.1'&&plan.developmentIdentity==='1.7.1-dev.1','successor identity drifted');
 req(plan.sourceRevision===SOURCE&&plan.sourceModelVersion===SOURCE_MODEL&&plan.section48QualificationModelVersion===SOURCE_MODEL,'source/model binding drifted');
 req(plan.stableBaseline===STABLE&&plan.historicalSourceStableBaseline===HISTORICAL,'stable baseline binding drifted');
 req(plan.consumerEligible===false,'plan must remain non-consumer-eligible');
 req(JSON.stringify(plan.evidenceTypes)===JSON.stringify(types),'evidence type set drifted');
 for(const t of types){
   req(JSON.stringify(plan.laneIdsByEvidenceType[t])===JSON.stringify(expected[t]),'lane set drifted: '+t);
   for(const id of expected[t]){const lane=laneMap.get(id); req(lane,'unknown Section 48 lane: '+id); req(lane.evidenceTypes.includes(t),'model no longer permits '+t+' for '+id);}
 }
 req(plan.companionEvidenceAutomaticallyInherited===false,'companion evidence must not auto-inherit');
 for(const paths of Object.values(plan.companionMethodControls))for(const rel of paths)req(fs.existsSync(path.join(root,rel)),'companion method missing: '+rel);
 for(const key of ['humanEvidenceEstablished','deviceEvidenceEstablished','assistiveTechnologyEvidenceEstablished','performanceEvidenceEstablished','energyEvidenceEstablished','companionEvidenceAutomaticallyInherited','section48EvidenceInventoryComplete','section48Accepted','v171AcceptanceEstablished','lifecyclePromotionEstablished','consumerAcceptanceEstablished','deploymentAcceptanceEstablished','publicationEstablished','productionAcceptanceEstablished']) req(plan.currentBoundary[key]===false,'current boundary overclaim: '+key);
 req(read('VERSION').trim()===STABLE,'bounded Stable VERSION changed');
 req(lifecycle.currentOfficial===STABLE&&lifecycle.currentStable===STABLE&&lifecycle.currentLifecycle==='anchor','bounded Stable authority changed');
 req(lifecycle.plannedNext==='1.7.1'&&lifecycle.activeCandidate===null&&lifecycle.activePatchReleaseCandidate===null,'successor lifecycle boundary changed');
 const head=git('rev-parse','HEAD'); req(HEX40.test(head),'tooling HEAD invalid'); git('cat-file','-e',SOURCE+'^{commit}'); execFileSync('git',['merge-base','--is-ancestor',SOURCE,head],{cwd:root});
 for(const phrase of ['not automatically inherited','real physical hardware','real assistive technology','Hosted CI is not representative-performance evidence','do not invent one','candidate evidence']) req(procedure.toLowerCase().includes(phrase.toLowerCase()),'procedure missing concept: '+phrase);
 for(const [t,record] of Object.entries(templates)){req(record.evidenceType===t,'template evidence type drifted: '+t); req(record.sourceRevision===SOURCE,'template source drifted: '+t); req(record.manualExecution===false,'template must begin fail-closed: '+t); authorityFalse(record.authority,'evidenceAccepted'); authorityFalse(record.authority,'laneClosed'); authorityFalse(record.authority,'section48Accepted'); authorityFalse(record.authority,'v171AcceptanceClaimed');}
 return head;
}
function common(r,type){
 req(r&&typeof r==='object'&&!Array.isArray(r),'record must be object'); req(r.recordType==='glaze-v1.7.1-section48-'+type+'-candidate','record type mismatch'); req(r.evidenceType===type,'evidence type mismatch'); req(r.sourceRevision===SOURCE,'source revision mismatch'); req(HEX40.test(String(r.toolingRevision||'')),'tooling revision invalid'); req(r.repository==='GoreeCloud/glaze','repository mismatch'); req(validDate(r.capturedAt),'capturedAt invalid'); meaningful(r.operator,'operator'); req(r.manualExecution===true,'manualExecution must be true'); req(expected[type].includes(r.laneId),'lane not eligible for '+type); const lane=laneMap.get(r.laneId); req(lane&&lane.evidenceTypes.includes(type),'qualification model disallows type for lane');
 req(r.integration&&typeof r.integration==='object','integration identity required'); meaningful(r.integration.repository,'integration repository'); req(HEX40.test(String(r.integration.revision||'')),'integration revision invalid'); meaningful(r.integration.buildIdentifier,'build identifier'); observations(r.observations); meaningful(r.summary,'summary'); meaningful(r.limitations,'limitations');
 const a=r.authority; req(a&&a.candidateEvidenceOnly===true,'candidateEvidenceOnly must be true'); for(const k of ['durableEvidenceRecorded','evidenceAccepted','laneClosed','section48Accepted','v171AcceptanceClaimed','lifecyclePromotionAutomatic','consumerAcceptanceAutomatic','deploymentAcceptanceAutomatic','publicationAutomatic','productionAcceptanceAutomatic']) authorityFalse(a,k);
}
function validateHuman(r){common(r,'human'); req(r.decision==='session-pass'||r.decision==='session-fail','human decision invalid'); req(r.environment&&r.environment.representative===true,'human environment must be reviewer-confirmed representative'); meaningful(r.environment.platformFamily,'human platform family'); meaningful(r.environment.runtime,'human runtime'); meaningful(r.environment.hardware,'human hardware'); if(r.laneId==='cross-platform-expression-v13'){const p=[...new Set(r.environment.platformFamiliesObserved||[])]; req(p.length>=2,'cross-platform human record requires >=2 platform families');} authorityFalse(r.authority,'deviceEvidenceAccepted'); authorityFalse(r.authority,'assistiveTechnologyEvidenceAccepted');}
function validateDevice(r){common(r,'device'); req(r.decision==='session-pass'||r.decision==='session-fail','device decision invalid'); const d=r.device; req(d&&d.physicalDevice===true&&d.emulator===false,'Device evidence requires real non-emulated physical device'); for(const k of ['manufacturer','model','platformFamily','osName','osVersion','formFactor']) meaningful(d[k],'device '+k); if(r.laneId==='compact-device-behavior-v13')req(['mobile','wearable','foldable','compact'].includes(String(d.formFactor).toLowerCase()),'compact-device lane requires actual compact form factor'); if(r.laneId==='cross-platform-expression-v13'){const p=[...new Set(d.platformFamiliesObserved||[])]; req(p.length>=2,'cross-platform device record requires >=2 platform families');} authorityFalse(r.authority,'humanEvidenceAccepted'); authorityFalse(r.authority,'energyEvidenceAccepted');}
function validateAT(r){common(r,'assistive-technology'); req(r.decision==='session-pass'||r.decision==='session-fail','AT decision invalid'); req(r.device&&r.device.physicalDevice===true,'AT session requires physical device'); for(const k of ['manufacturer','model','osName','osVersion']) meaningful(r.device[k],'AT device '+k); const a=r.assistiveTechnology; for(const k of ['name','version','inputMode']) meaningful(a?.[k],'assistive technology '+k); const desc=(a.name+' '+a.inputMode).toLowerCase(); if(r.laneId==='switch-access-v13')req(desc.includes('switch'),'switch-access lane requires switch technology'); if(r.laneId==='voice-access-v13')req(desc.includes('voice'),'voice-access lane requires voice technology'); authorityFalse(r.authority,'humanEvidenceAccepted'); authorityFalse(r.authority,'deviceEvidenceAccepted');}
function validatePerformance(r){common(r,'performance'); req(r.laneId==='performance-v13','performance record lane mismatch'); req(r.decision==='session-pass'||r.decision==='session-fail','performance decision invalid'); const e=r.environment; req(e&&e.representative===true&&e.foregroundState==='foreground','performance environment must be representative foreground'); for(const k of ['operatingSystem','runtime','hardware','presentationMode','measurementDate']) meaningful(e[k],'performance '+k); req(e.exactRevision===SOURCE&&e.lifecycle==='DevelopmentQualification','performance environment identity mismatch'); const s=r.samples; req(s.resolver>=200&&s.interactionPaint>=30&&s.idleFrames>=120&&s.activeFrames>=240,'performance sample minima not met'); const coverage=[...new Set(r.coveredSection48SurfaceIds||[])]; const required=plan.requiredSection48Coverage.surfaceIds; req(required.every(x=>coverage.includes(x)),'performance record must cover all governed Section 48 surface IDs'); const evaluation=evaluateGlazePerformanceMeasurements({environment:e,samples:s,measurements:r.measurements}); req((r.decision==='session-pass')===(evaluation.status==='pass'),'performance decision must match governed budget evaluator'); req(r.authority.hostedCiEvidence===false,'hosted CI cannot be performance evidence'); authorityFalse(r.authority,'deviceEvidenceAccepted'); authorityFalse(r.authority,'energyEvidenceAccepted');}
function validateEnergy(r){common(r,'energy'); req(r.laneId==='energy-v13','energy record lane mismatch'); req(r.decision==='review-required'||r.decision==='measurement-blocked','energy decision must remain review-required or blocked'); const d=r.device; req(d&&d.physicalDevice===true,'energy measurement requires physical device'); for(const k of ['manufacturer','model','platformFamily','osName','osVersion']) meaningful(d[k],'energy device '+k); const m=r.measurement; meaningful(m.method,'energy method'); req(energyMethodPlan.record.allowedMeasurementMethods.includes(m.method),'energy method is not governed by companion Energy protocol'); meaningful(m.unit,'energy unit'); for(const k of ['controlledIdle','foregroundSection48Workload','constrainedOrLowPower','backgroundOrOffscreen']) req(Number.isFinite(m[k]),'energy '+k+' must be quantitative'); req(m.thermalRecoveryObserved===true,'thermal/resource recovery must be observed'); req(Array.isArray(m.coveredSection48SurfaceIds)&&m.coveredSection48SurfaceIds.length>0,'energy Section 48 workload coverage required'); authorityFalse(r.authority,'deviceEvidenceAccepted'); authorityFalse(r.authority,'performanceEvidenceAccepted'); req(r.authority.numericAcceptanceThresholdInvented===false,'energy threshold must not be invented');}
const validators={human:validateHuman,device:validateDevice,'assistive-technology':validateAT,performance:validatePerformance,energy:validateEnergy};
function obs(){return [{id:'section48-field-observation',status:'pass',observation:'Synthetic validator fixture only; not accepted field evidence.',blockingFinding:null}];}
function base(head,type,lane){return {schemaVersion:1,recordType:'glaze-v1.7.1-section48-'+type+'-candidate',evidenceType:type,sourceRevision:SOURCE,toolingRevision:head,repository:'GoreeCloud/glaze',capturedAt:'2026-10-04T03:30:00Z',operator:'field-control-self-test',manualExecution:true,laneId:lane,integration:{repository:'GoreeCloud/glaze',revision:head,buildIdentifier:'self-test-build'},observations:obs(),decision:'session-pass',summary:'Synthetic control-plane self-test only; not accepted evidence.',limitations:'Synthetic fixture.',authority:{candidateEvidenceOnly:true,durableEvidenceRecorded:false,evidenceAccepted:false,laneClosed:false,section48Accepted:false,v171AcceptanceClaimed:false,lifecyclePromotionAutomatic:false,consumerAcceptanceAutomatic:false,deploymentAcceptanceAutomatic:false,publicationAutomatic:false,productionAcceptanceAutomatic:false}};}
function sample(head,type){const lane=expected[type][0],r=base(head,type,lane); if(type==='human'){r.environment={platformFamily:'linux',runtime:'self-test',hardware:'self-test',representative:true,platformFamiliesObserved:['linux','android']}; Object.assign(r.authority,{deviceEvidenceAccepted:false,assistiveTechnologyEvidenceAccepted:false,performanceEvidenceAccepted:false,energyEvidenceAccepted:false});} if(type==='device'){r.device={physicalDevice:true,emulator:false,manufacturer:'Self Test',model:'Physical Fixture',platformFamily:'linux',osName:'Test OS',osVersion:'1',formFactor:'desktop',inputCapabilities:['keyboard'],platformFamiliesObserved:['linux','android']}; Object.assign(r.authority,{humanEvidenceAccepted:false,energyEvidenceAccepted:false});} if(type==='assistive-technology'){r.device={physicalDevice:true,manufacturer:'Self Test',model:'Physical Fixture',osName:'Test OS',osVersion:'1'}; r.assistiveTechnology={name:'Orca',version:'1',inputMode:'screen-reader'}; Object.assign(r.authority,{humanEvidenceAccepted:false,deviceEvidenceAccepted:false});} if(type==='performance'){r.environment={exactRevision:SOURCE,lifecycle:'DevelopmentQualification',operatingSystem:'Representative OS',runtime:'Representative Runtime',hardware:'Representative Hardware',foregroundState:'foreground',presentationMode:'normal',measurementDate:'2026-10-03',representative:true}; r.samples={resolver:200,interactionPaint:30,idleFrames:120,activeFrames:240}; r.measurements={resolverP95Ms:9.5,resolverP99Ms:16,interactionPaintP95Ms:90,interactionPaintP99Ms:180,idleMedianFrameIntervalMs:16.7,activeFrameP95Ms:20,severeFrameStallRate:0.005,catastrophicForegroundStallCount:0,taskStateResetCount:0,pageReloadRequiredCount:0,automaticAuthorityActionCount:0}; r.coveredSection48SurfaceIds=[...plan.requiredSection48Coverage.surfaceIds]; Object.assign(r.authority,{hostedCiEvidence:false,deviceEvidenceAccepted:false,energyEvidenceAccepted:false});} if(type==='energy'){r.decision='review-required'; r.device={physicalDevice:true,manufacturer:'Self Test',model:'Physical Fixture',platformFamily:'linux',osName:'Test OS',osVersion:'1'}; r.measurement={method:'platform-energy-instrument',unit:'joules',controlledIdle:1,foregroundSection48Workload:2,constrainedOrLowPower:1.5,backgroundOrOffscreen:1.2,thermalRecoveryObserved:true,coveredSection48SurfaceIds:['expression-system']}; Object.assign(r.authority,{deviceEvidenceAccepted:false,performanceEvidenceAccepted:false,numericAcceptanceThresholdInvented:false});} return r;}
function reject(fn,r,label){let threw=false; try{fn(r);}catch{threw=true;} req(threw,'self-test expected rejection: '+label);}
function selfTest(head){for(const t of types)validators[t](sample(head,t)); const stale=sample(head,'human'); stale.sourceRevision='0'.repeat(40); reject(validateHuman,stale,'stale source'); const emu=sample(head,'device'); emu.device.emulator=true; reject(validateDevice,emu,'emulator device'); const cross=sample(head,'device'); cross.laneId='cross-platform-expression-v13'; cross.device.platformFamiliesObserved=['linux']; reject(validateDevice,cross,'single-platform cross-platform claim'); const sw=sample(head,'assistive-technology'); sw.laneId='switch-access-v13'; reject(validateAT,sw,'switch lane without switch technology'); const ci=sample(head,'performance'); ci.authority.hostedCiEvidence=true; reject(validatePerformance,ci,'hosted CI performance'); const short=sample(head,'performance'); short.samples.activeFrames=10; reject(validatePerformance,short,'short performance samples'); const proxy=sample(head,'energy'); proxy.measurement.method='battery-percent'; reject(validateEnergy,proxy,'proxy energy method'); for(const t of types)reject(validators[t],structuredClone(templates[t]),'fail-closed template '+t);}
const head=validateSource();
const args=process.argv.slice(2); if(args.includes('--self-test')){selfTest(head); console.log('Glaze V1.7.1 Section 48 field qualification control self-test: PASS'); console.log('Synthetic self-test records are not field evidence.');}
for(const t of types){const flag='--'+t+'-record'; const i=args.indexOf(flag); if(i>=0){req(args[i+1],'missing '+flag+' path'); validators[t](JSON.parse(fs.readFileSync(path.resolve(args[i+1]),'utf8'))); console.log('Validated Section 48 '+t+' candidate record.');}}
if(args.length===0)console.log('Glaze V1.7.1 Section 48 field qualification control source validation: PASS');
console.log('Frozen source: '+SOURCE+' / '+SOURCE_MODEL); console.log('Field evidence types: '+types.join(', ')); console.log('Candidate records automatically accepted: false'); console.log('Section 48 accepted by this control: false'); console.log('Current bounded Stable preserved: '+STABLE);
